// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Message struct {
	ID            string  `json:"id"`
	SessionID     string  `json:"session_id"`
	Role          string  `json:"role"`
	Position      int64   `json:"position"`
	Content       string  `json:"content"`
	ProviderRunID *string `json:"provider_run_id"`
	CreatedAt     int64   `json:"created_at"`
}

type Part struct {
	ID            string  `json:"id"`
	MessageID     string  `json:"message_id"`
	SessionID     string  `json:"session_id"`
	Type          string  `json:"type"`
	Content       string  `json:"content"`
	Position      int64   `json:"position"`
	Metadata      *string `json:"metadata"`
	ProviderRunID *string `json:"provider_run_id"`
	CreatedAt     int64   `json:"created_at"`
}

type Project struct {
	ID        string `json:"id"`
	Path      string `json:"path"`
	CreatedAt int64  `json:"created_at"`
	RemovedAt *int64 `json:"removed_at"`
}

type Session struct {
	ID           string  `json:"id"`
	ProjectID    string  `json:"project_id"`
	WorktreeID   string  `json:"worktree_id"`
	Title        *string `json:"title"`
	Status       string  `json:"status"`
	Version      int64   `json:"version"`
	HasSummary   int64   `json:"has_summary"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
}

type Worktree struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Path             string `json:"path"`
	IsLinkedWorktree int64  `json:"is_linked_worktree"`
	ExpandedState    int64  `json:"expanded_state"`
	CreatedAt        int64  `json:"created_at"`
}
