// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, session_id, role, position, content)
VALUES (?, ?, ?, ?, ?)
RETURNING id, session_id, role, position, content, provider_run_id, created_at
`

type CreateMessageParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Position  int64  `json:"position"`
	Content   string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Position,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Position,
		&i.Content,
		&i.ProviderRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createPart = `-- name: CreatePart :one
INSERT INTO parts (id, message_id, session_id, type, content, position, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, message_id, session_id, type, content, position, metadata, provider_run_id, created_at
`

type CreatePartParams struct {
	ID        string  `json:"id"`
	MessageID string  `json:"message_id"`
	SessionID string  `json:"session_id"`
	Type      string  `json:"type"`
	Content   string  `json:"content"`
	Position  int64   `json:"position"`
	Metadata  *string `json:"metadata"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRowContext(ctx, createPart,
		arg.ID,
		arg.MessageID,
		arg.SessionID,
		arg.Type,
		arg.Content,
		arg.Position,
		arg.Metadata,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SessionID,
		&i.Type,
		&i.Content,
		&i.Position,
		&i.Metadata,
		&i.ProviderRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, position, content, provider_run_id, created_at
FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Position,
		&i.Content,
		&i.ProviderRunID,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, position, content, provider_run_id, created_at
FROM messages
WHERE session_id = ?
ORDER BY position ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Position,
			&i.Content,
			&i.ProviderRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsByMessage = `-- name: ListPartsByMessage :many
SELECT id, message_id, session_id, type, content, position, metadata, provider_run_id, created_at
FROM parts
WHERE message_id = ?
ORDER BY position ASC
`

func (q *Queries) ListPartsByMessage(ctx context.Context, messageID string) ([]Part, error) {
	rows, err := q.db.QueryContext(ctx, listPartsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.SessionID,
			&i.Type,
			&i.Content,
			&i.Position,
			&i.Metadata,
			&i.ProviderRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsBySession = `-- name: ListPartsBySession :many
SELECT id, message_id, session_id, type, content, position, metadata, provider_run_id, created_at
FROM parts
WHERE session_id = ?
ORDER BY position ASC
`

func (q *Queries) ListPartsBySession(ctx context.Context, sessionID string) ([]Part, error) {
	rows, err := q.db.QueryContext(ctx, listPartsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.SessionID,
			&i.Type,
			&i.Content,
			&i.Position,
			&i.Metadata,
			&i.ProviderRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessagePosition = `-- name: NextMessagePosition :one
SELECT COALESCE(MAX(position), -1) + 1
FROM messages
WHERE session_id = ?
`

func (q *Queries) NextMessagePosition(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMessagePosition, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
