// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"
)

const addWorktree = `-- name: AddWorktree :one
INSERT INTO worktrees (id, project_id, path, is_linked_worktree, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, path, is_linked_worktree, created_at
`

type AddWorktreeParams struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Path             string `json:"path"`
	IsLinkedWorktree int64  `json:"is_linked_worktree"`
	CreatedAt        int64  `json:"created_at"`
}

func (q *Queries) AddWorktree(ctx context.Context, arg AddWorktreeParams) (Worktree, error) {
	row := q.db.QueryRowContext(ctx, addWorktree,
		arg.ID,
		arg.ProjectID,
		arg.Path,
		arg.IsLinkedWorktree,
		arg.CreatedAt,
	)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.IsLinkedWorktree,
		&i.CreatedAt,
	)
	return i, err
}

const archiveSession = `-- name: ArchiveSession :exec
UPDATE sessions
SET status = 'archived', updated_at = ?
WHERE id = ?
`

type ArchiveSessionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ArchiveSession(ctx context.Context, arg ArchiveSessionParams) error {
	_, err := q.db.ExecContext(ctx, archiveSession, arg.UpdatedAt, arg.ID)
	return err
}

const countSessionsByProject = `-- name: CountSessionsByProject :one
SELECT COUNT(*) FROM sessions WHERE project_id = ?
`

func (q *Queries) CountSessionsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, path, expanded_state, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, path, expanded_state, created_at, removed_at
`

type CreateProjectParams struct {
	ID            string `json:"id"`
	Path          string `json:"path"`
	ExpandedState int64  `json:"expanded_state"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Path,
		arg.ExpandedState,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, project_id, worktree_id, worktree_path,
    status, version, has_summary, created_at, updated_at, last_active_at
) VALUES (?, ?, ?, ?, 'active', 1, 0, ?, ?, ?)
RETURNING
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
`

type CreateSessionParams struct {
	ID           string  `json:"id"`
	ProjectID    string  `json:"project_id"`
	WorktreeID   *string `json:"worktree_id"`
	WorktreePath string  `json:"worktree_path"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.WorktreeID,
		arg.WorktreePath,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastActiveAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.Title,
		&i.Status,
		&i.Version,
		&i.HasSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const findProjectByPath = `-- name: FindProjectByPath :one
SELECT id, path, expanded_state, created_at, removed_at
FROM projects
WHERE path = ?
`

func (q *Queries) FindProjectByPath(ctx context.Context, path string) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectByPath, path)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findWorktreeById = `-- name: FindWorktreeById :one
SELECT id, project_id, path, is_linked_worktree, created_at
FROM worktrees WHERE id = ?
`

func (q *Queries) FindWorktreeById(ctx context.Context, id string) (Worktree, error) {
	row := q.db.QueryRowContext(ctx, findWorktreeById, id)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.IsLinkedWorktree,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, path, expanded_state, created_at, removed_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.Title,
		&i.Status,
		&i.Version,
		&i.HasSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, path, expanded_state, created_at, removed_at
FROM projects
WHERE removed_at IS NULL
ORDER BY created_at DESC, rowid DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ExpandedState,
			&i.CreatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMetadata = `-- name: ListSessionMetadata :many
SELECT
    id, project_id, worktree_id, worktree_path,
    title, status, created_at, updated_at, last_active_at
FROM sessions
ORDER BY last_active_at DESC
`

type ListSessionMetadataRow struct {
	ID           string  `json:"id"`
	ProjectID    string  `json:"project_id"`
	WorktreeID   *string `json:"worktree_id"`
	WorktreePath string  `json:"worktree_path"`
	Title        *string `json:"title"`
	Status       string  `json:"status"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
}

// Slim rows for sidebar tree nesting (excludes version / has_summary).
func (q *Queries) ListSessionMetadata(ctx context.Context) ([]ListSessionMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionMetadataRow
	for rows.Next() {
		var i ListSessionMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorktreeID,
			&i.WorktreePath,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateProject = `-- name: ReactivateProject :one
UPDATE projects SET removed_at = NULL WHERE id = ?
RETURNING id, path, expanded_state, created_at, removed_at
`

func (q *Queries) ReactivateProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, reactivateProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softRemoveProject = `-- name: SoftRemoveProject :one
UPDATE projects SET removed_at = ? WHERE id = ?
RETURNING id, path, expanded_state, created_at, removed_at
`

type SoftRemoveProjectParams struct {
	RemovedAt *int64 `json:"removed_at"`
	ID        string `json:"id"`
}

func (q *Queries) SoftRemoveProject(ctx context.Context, arg SoftRemoveProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, softRemoveProject, arg.RemovedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const updateProjectExpandedState = `-- name: UpdateProjectExpandedState :exec
UPDATE projects
SET expanded_state = ?
WHERE id = ?
`

type UpdateProjectExpandedStateParams struct {
	ExpandedState int64  `json:"expanded_state"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateProjectExpandedState(ctx context.Context, arg UpdateProjectExpandedStateParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectExpandedState, arg.ExpandedState, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET title = ?, updated_at = ?, last_active_at = ?
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title        *string `json:"title"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle,
		arg.Title,
		arg.UpdatedAt,
		arg.LastActiveAt,
		arg.ID,
	)
	return err
}
