// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"
)

const archiveSession = `-- name: ArchiveSession :exec
UPDATE sessions
SET status = 'archived', updated_at = ?
WHERE id = ?
`

type ArchiveSessionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ArchiveSession(ctx context.Context, arg ArchiveSessionParams) error {
	_, err := q.db.ExecContext(ctx, archiveSession, arg.UpdatedAt, arg.ID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, path, expanded_state, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, path, expanded_state, created_at
`

type CreateProjectParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Path          string `json:"path"`
	ExpandedState int64  `json:"expanded_state"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.ExpandedState,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, project_id, worktree_id, worktree_path,
    status, version, has_summary, created_at, updated_at, last_active_at
) VALUES (?, ?, ?, ?, 'active', 1, 0, ?, ?, ?)
RETURNING
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
`

type CreateSessionParams struct {
	ID           string  `json:"id"`
	ProjectID    string  `json:"project_id"`
	WorktreeID   *string `json:"worktree_id"`
	WorktreePath string  `json:"worktree_path"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.WorktreeID,
		arg.WorktreePath,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastActiveAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.Title,
		&i.Status,
		&i.Version,
		&i.HasSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, path, expanded_state, created_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.Title,
		&i.Status,
		&i.Version,
		&i.HasSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
FROM sessions
ORDER BY last_active_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorktreeID,
			&i.WorktreePath,
			&i.Title,
			&i.Status,
			&i.Version,
			&i.HasSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, expanded_state, created_at
FROM projects
ORDER BY created_at DESC, rowid DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.ExpandedState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT
    id, project_id, worktree_id, worktree_path,
    title, status, version, has_summary, created_at, updated_at, last_active_at
FROM sessions
WHERE project_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorktreeID,
			&i.WorktreePath,
			&i.Title,
			&i.Status,
			&i.Version,
			&i.HasSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectExpandedState = `-- name: UpdateProjectExpandedState :one
UPDATE projects
SET expanded_state = ?
WHERE id = ?
RETURNING id, name, path, expanded_state, created_at
`

type UpdateProjectExpandedStateParams struct {
	ExpandedState int64  `json:"expanded_state"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateProjectExpandedState(ctx context.Context, arg UpdateProjectExpandedStateParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectExpandedState, arg.ExpandedState, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ExpandedState,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET title = ?, updated_at = ?, last_active_at = ?
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title        *string `json:"title"`
	UpdatedAt    int64   `json:"updated_at"`
	LastActiveAt int64   `json:"last_active_at"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle,
		arg.Title,
		arg.UpdatedAt,
		arg.LastActiveAt,
		arg.ID,
	)
	return err
}
